[package]
name = "app"
version = "0.1.0"
edition = "2024"

[dependencies]
askama = "0.16"
async-trait = "0.1"
axum = "0.8"
gethostname = "1"
hickory-server = "0.26"
memory-serve = { version = "2", features = ["force-embed"] }
reqwest = "0.13"
serde = { version = "1", features = ["derive"] }
tokio = { version = "1", features = ["full"] }

[build-dependencies]
memory-serve = { version = "2", features = ["force-embed"] }
